version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb_container
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root12345
    ports:
      - '27107:27107'
    volumes:
      - ./data:/data/db
